version: "3.8"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventhub_db
      MYSQL_USER: event
      MYSQL_PASSWORD: admin
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql_config/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"


  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: fastapi_backend
    restart: always
    environment:
      DATABASE_URL: mysql+pymysql://event:admin@mysql:3306/eventhub_db
    ports:
      - "8081:8081"
    depends_on:
      - mysql


  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend